### PR TITLE
LuaJIT and Lua 5.1 compatibility layer

### PR DESCRIPTION
**Pull request by ThePhD**
This pull request adds support for Lua 5.1 through a compatibility layer as per the question in Issue #56. This also means LuaJIT can now work with sol.

Note that luajit is much less kinda that vanilla Lua and mistakes such as not passing the correct number of parameters and the like is punished with segfaults.

This PR also updates the copyright headers and fixes some tests to prevent luajit program termination because of badly written lua code.

### CODE REVIEW

**Comment by mallochine** [comment]
I tried this pull request with my luajit 2.0.3 and following code snippet isn't compiling.

```
#define LUA_VERSION "Lua 5.1"
#define LUA_RELEASE "Lua 5.1.4"
```

```
#include <lua.hpp>
#include <sol.hpp>
int main() {
  sol::state lua;
  lua.open_libraries(sol::lib::base);
  lua.open_file(file);
  auto it = lua.get<sol::function>("test_lua");
  it.call<>();
  return 0;
}
```

and 

```
function test_lua()
  file = io.open("/home/aguo/random_shit", "a")
  file:write("TROLOLOLOLLOLOLOLLOLO\n")
  file:close()
  return true
end
```

Failing compilng errors were:

/usr/include/sol/stack.hpp:100:31: error: use of undeclared identifier 'lua_tounsigned'
        return static_cast<U>(lua_tounsigned(L, index));
                              ^
In file included from /home/nutanix/hmain/stats/arithmos/master/arithmos_master.cc:10:
In file included from /usr/include/sol.hpp:25:
In file included from /usr/include/sol/state.hpp:26:
/usr/include/sol/table.hpp:103:16: error: use of undeclared identifier 'lua_rawlen'
        return lua_rawlen(state(), -1);
               ^
In file included from /home/nutanix/hmain/stats/arithmos/master/arithmos_master.cc:10:
In file included from /usr/include/sol.hpp:25:
/usr/include/sol/state.hpp:61:27: error: use of undeclared identifier 'LUA_RIDX_GLOBALS'
    global(reg.get<table>(LUA_RIDX_GLOBALS)) {
                          ^
/usr/include/sol/state.hpp:82:17: error: use of undeclared identifier 'luaL_requiref'
                luaL_requiref(L.get(), "base", luaopen_base, 1);
                ^
/usr/include/sol/state.hpp:86:17: error: use of undeclared identifier 'luaL_requiref'
                luaL_requiref(L.get(), "package", luaopen_package, 1);
                ^
/usr/include/sol/state.hpp:90:53: error: use of undeclared identifier 'luaopen_coroutine'
                luaL_requiref(L.get(), "coroutine", luaopen_coroutine, 1);
                                                    ^
/usr/include/sol/state.hpp:94:17: error: use of undeclared identifier 'luaL_requiref'
                luaL_requiref(L.get(), "string", luaopen_string, 1);
                ^
/usr/include/sol/state.hpp:98:17: error: use of undeclared identifier 'luaL_requiref'
                luaL_requiref(L.get(), "table", luaopen_table, 1);
                ^
/usr/include/sol/state.hpp:102:17: error: use of undeclared identifier 'luaL_requiref'
                luaL_requiref(L.get(), "math", luaopen_math, 1);
                ^
/usr/include/sol/state.hpp:106:49: error: use of undeclared identifier 'luaopen_bit32'
                luaL_requiref(L.get(), "bit32", luaopen_bit32, 1);
                                                ^
/usr/include/sol/state.hpp:110:17: error: use of undeclared identifier 'luaL_requiref'
                luaL_requiref(L.get(), "io", luaopen_io, 1);
                ^
/usr/include/sol/state.hpp:114:17: error: use of undeclared identifier 'luaL_requiref'
                luaL_requiref(L.get(), "os", luaopen_os, 1);
                ^
/usr/include/sol/state.hpp:118:17: error: use of undeclared identifier 'luaL_requiref'
                luaL_requiref(L.get(), "debug", luaopen_debug, 1);
                ^
13 errors generated.

**Comment by mallochine** [comment]
Apologies. Things are looking better when I pulled from your "develop" branch.

**Comment by mallochine** [comment]
I am running into the following error thouhg:

In file included from /home/nutanix/hmain/stats/arithmos/master/arithmos_master.cc:10:
In file included from /usr/include/sol.hpp:25:
/usr/include/sol/state.hpp:98:18: error: duplicate case value 'coroutine'
            case lib::coroutine:

```
   9 #include <lua.hpp>
  10 #include <sol.hpp>
```

**Comment by mallochine** [comment]
now this one looks like a legit bug in Sol. There's a lot of confusing logic going on in "sol/compatibility/version.hpp". I kinda cringed when I saw that.

**Comment by ThePhD** [comment]
I had put the `#if`'s on the wrong line, @mallochine. Should be okay now...

**Comment by ThePhD** [comment]
@Rapptz  There are a bunch of conflicts in this branch now, but I think that aside from the changes to make luajit/lua-5.1 work, I've made some pretty great changes on the automatic decay of the proxy objects (I added a new one called function_result).

It allows users to get a function from sol and call it regularly:

```
sol::function f = lua["lua_func_returns_string"];
std::string mystr = f(); // no .call<std::string>() required
```

I use the string example here because before we couldn't decay to std::string without overload resolution problems for the operator= and std::string constructor. I employed tons of enable_if to the implicit conversion operator of `proxy` and `function_result` to make it no longer an issue.

I do have a request: could you give the latest in my develop branch a test on g++/clang++ to make sure there's still no error (and that my code is also correct on those compilers)? I've cleaned out my computer and my clang++/g++ installs are currently dead in the water.

**Comment by Rapptz** [comment]
I'll deal with it at a later date when I work out all the conflicts. No worries.

**Comment by ThePhD** [comment]
This commit now has the ability to return a function result if you don't coerce the return value to a typed element. This allows you to check if the function call as failed or not. If you specify a specific return value, however, the system will simply use the `atpanic` function provided to handle errors (as lua is known to do).

**Comment by Nava2** [comment]
With LuaJIT: `#define LUAJIT_VERSION        "LuaJIT 2.0.3"`, the functions `lua_pcallk` and `lua_callk` do not exist, however, `lua_call` and `lua_pcall` do exist and in Lua 5.2 they are identical in usage to the two uses within `function.hpp`.

Might I suggest replacing the `k` variants with their simpler versions for compatibility?

``` diff
diff --git a/sol/function.hpp b/sol/function.hpp
index db6bfc7..4da6068 100644
--- a/sol/function.hpp
+++ b/sol/function.hpp
@@ -140,11 +140,11 @@ private:
     };

     int luacodecall(std::ptrdiff_t argcount, std::ptrdiff_t resultcount, handler& h) const {
-        return lua_pcallk(state(), static_cast<int>(argcount), static_cast<int>(resultcount), h.stack, 0, nullptr);
+        return lua_pcall(state(), static_cast<int>(argcount), static_cast<int>(resultcount), h.stack);
     }

     void luacall(std::ptrdiff_t argcount, std::ptrdiff_t resultcount, handler& h) const {
-        lua_callk(state(), static_cast<int>(argcount), static_cast<int>(resultcount), 0, nullptr);
+        lua_call(state(), static_cast<int>(argcount), static_cast<int>(resultcount));
     }

     template<std::size_t... I, typename... Ret>
diff --git a/sol/types.hpp b/sol/types.hpp
index 574e134..72f7a6c 100644
--- a/sol/types.hpp
+++ b/sol/types.hpp
@@ -63,11 +63,13 @@ enum class call_syntax {
 };

 enum class call_error : int {
-       ok = LUA_OK,
-       runtime = LUA_ERRRUN,
-       memory = LUA_ERRMEM,
-       handler = LUA_ERRERR,
-       gc = LUA_ERRGCMM
+      ok = LUA_OK
+    , runtime = LUA_ERRRUN
+    , memory = LUA_ERRMEM
+    , handler = LUA_ERRERR
+#if LUA_VERSION_NUM > 502
+    , gc = LUA_ERRGCMM
+#endif^M
 };

 enum class type : int {
```

Also, luajit does not export `LUA_ERRGCMM`, I'm unsure of the version requirements for that. :-1:

**Comment by ThePhD** [comment]
This is fixed in `sol2`.

**Pull request closed without merging**
